name = "Container of Create"
author = "l0py2"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9085c40ce551a6d3e5bda23c4c48a9602d48715630de5bf6614b8b3a80c29448"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
