name = "Container of Create"
author = "l0py2"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b14ce5620687b8191a88184b95d12038d86470e36a2fb1d6a0e1527022dca59a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
