name = "Container of Create"
author = "l0py2"
version = "0.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdbd4de7da4015b4bec778ea3651f804b24cac43d9a84eb5cd1e96e5522761e6"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
