name = "Container of Create"
author = "l0py2"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ce49a433619888d975ad27f77bdbcb0b17b11e29f4aa0c8fbda8752c684f1ce"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
