name = "Container of Create"
author = "l0py2"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5db157216aa480065464a504574b590385ffc204cb806f4119f24e5f182f4301"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
