name = "Container of Create"
author = "l0py2"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "572d658877daa7d88b7df05d5f4b24b62944ac035a2ee7604f3153efcdd4724d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
