name = "Container of Create"
author = "l0py2"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c07248b52b7c92137af1d040c056de73a02b609c7a9b7859447700297a984a6"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
