name = "Container of Create"
author = "l0py2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29ba6ee5c1931ce1eabfee0f165a0c38a1b4d307fb6daccd8d73fa9e7907aa6e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
