name = "Container of Create"
author = "l0py2"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34253c8e620e7ed3d65682e6a73146239e16068beb4a9553aa445ac65a2f0666"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
