name = "Container of Create"
author = "l0py2"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b52dffde87554e20c544fed26d4ec81b4b908c8e6cacd7b5b81acaeb33a3e8f"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
