name = "Container of Create"
author = "l0py2"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aae4213a4ea325993431996bcf3e44c8eeeb5205e0fe7742e62874399289e8a"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
