name = "Container of Create"
author = "l0py2"
version = "0.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b071814c7e743b6ab66419d4957259fff19c35dc4afc818cb85a38eff42ddc7"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
