name = "Container of Create"
author = "l0py2"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d893764b7087874e168d97c8d1a921003bd34e4b199d1523ccf56026cbe8b99"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
