name = "Container of Create"
author = "l0py2"
version = "0.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aefa6c7ce9377e09106e29fb15c5306c2c8b3f064abfb27231d8d773fe3efda9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
