name = "Container of Create"
author = "l0py2"
version = "0.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee05f4459c056f0323782c0e0555017b4a685666590eeeaa963cd399e8269992"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
