name = "Container of Create"
author = "l0py2"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d896c5c7139527856eec0c223ae81e60e2f0801eae8cff50ffb72c20df4d154b"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
