name = "Container of Create"
author = "l0py2"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20bfc80b0d4b9a566ffe16b7831901da4a575bf66a546fc7a0b07eb9f38ce955"

[versions]
forge = "43.2.22"
minecraft = "1.19.2"
