name = "Container of Create"
author = "l0py2"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b71d013c65aad96df11076e3da1362925adf8cc5964716e5c4150ed15d014a83"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
