name = "Container of Create"
author = "l0py2"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84219f0076532afc2379d7f35f4965438077fb9486b0ddcbda755077c8554bc6"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
