name = "Container of Create"
author = "l0py2"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "350d3c2517ad945fd6f009ce223fa3cc890512c67ad6e63dbfb7f1c387b0037e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
