name = "Container of Create"
author = "l0py2"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f3b2931d430c4092c1a0527eef39ab6f6aad1a9a649e8f7d6619d8d94fa9d2b"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
