name = "Container of Create"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6a30a9d7f5a1151e35560841b6c41cf8b3733a6e28b104b03a0effd601ce1a9"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"
