name = "Container of Create"
author = "l0py2"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7185d42438f303e2bcf6945b122cf283fe04232a62e39d420976b26589a4116c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
