name = "Container of Create"
author = "l0py2"
version = "0.11.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4433cdd21dd85dcf5895c6dd4753e8d46fdcd1ddc38176cf32b31141877c7d96"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
