name = "Container of Create"
author = "l0py2"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5174b32b7ce1936f247349494f78aa337e5a7b0ac44a38954a40e98561601b84"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
