name = "Container of Create"
author = "l0py2"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7d607568cdc9e59f5dc968b4bea3c0743b5105d728f51dad81a55c76627dfaa"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"
