name = "Container of Create"
author = "l0py2"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17eb3c7b7a99d1889f343bc08be81e4b26b48ed35e8c8a4028724117877524c9"

[versions]
forge = "43.2.22"
minecraft = "1.19.2"
