name = "Container of Create"
author = "l0py2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "474b92d84d4ef1271cf702b57f1db89d413348ff980e1c0a3e5be78a1dc12a65"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
