// prioriry: 0

global.removedOres = [
	'tfmg:lead_ore',
	'tfmg:deepslate_lead_ore',
	'tfmg:nickel_ore',
	'tfmg:deepslate_nickel_ore'
];

global.removedItems = [
	'ad_astra:coal_generator',
	'ad_astra:compressor',
	'ad_astra:energizer',
	'ad_astra:etrionic_blast_furnace',
	'ad_astra:iron_plate',
	'ad_astra:iron_rod',
	'ad_astra:oil_bucket',
	'ad_astra:steel_ingot',
	'ad_astra:steel_nugget',
	'ad_astra:steel_plate',
	'aquaculture:diamond_fillet_knife',
	'aquaculture:gold_fillet_knife',
	'aquaculture:iron_fillet_knife',
	'aquaculture:stone_fillet_knife',
	'aquaculture:wooden_fillet_knife',
	'create:copper_nugget',
	'create:copper_sheet',
	'create:golden_sheet',
	'create:iron_sheet',
	'create_new_age:copper_wire',
	'create_new_age:electrical_connector',
	'create_new_age:overcharged_diamond_wire',
	'create_new_age:overcharged_golden_wire',
	'create_new_age:overcharged_iron_wire',
	'createaddition:alternator',
	'createaddition:electric_motor',
	'createaddition:electrum_sheet',
	'tfmg:accumulator',
	'tfmg:cable_connector',
	'tfmg:cable_tube',
	'tfmg:capacitor',
	'tfmg:copper_cable',
	'tfmg:copper_wire',
	'tfmg:diagonal_cable_block',
	'tfmg:galvanic_cell',
	'tfmg:heavy_plate',
	'tfmg:lead_ingot',
	'tfmg:nickel_ingot',
	'tfmg:raw_lead',
	'tfmg:raw_nickel',
	'tfmg:steel_ingot',
	'thermal:apple_block',
	'thermal:bamboo_block',
	'thermal:beetroot_block',
	'thermal:carrot_block',
	'thermal:energy_cell',
	'thermal:energy_minecart',
	'thermal:fluid_cell',
	'thermal:fluid_minecart',
	'thermal:machine_crafter',
	'thermal:machine_press',
	'thermal:potato_block',
	'thermal:sushi_maki',
	/^tfmg:.*_cable_hub$/,
	/^thermal:dynamo_(?!stirling).*/,
	/^thermal:flax.*/,
	/^thermal:onion.*/,
	/^thermal:press_.*_die$/,
	/^thermal:rice.*/,
	/^thermal:tomato.*/
];

global.removedItems = global.removedItems.concat(global.removedOres);
